Algoritmo "L05D"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa 
// Descrição   : Somatória de 1 até 500!(soma de 1 a 500)
// Autor(a)    : Bernardo Prieto
// Data atual  : 25/09/2023
Var
contadora,somatoria:inteiro



Inicio
para contadora de 1 ate 500 passo 1 faca
somatoria<-somatoria+contadora
fimpara
escreval("A soma de 1 até 500 é ",somatoria)




Fimalgoritmo