Algoritmo "L05F"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa 
// Descrição   : Números divisíveis por 4 de 1 até 200!
// (números divísveis por 4)
// Autor(a)    : Bernardo Prieto
// Data atual  : 25/09/2023
Var
contadora:inteiro



Inicio
para contadora de 1 ate 200 passo 1 faca
se (contadora mod 4 = 0) entao
escreval(contadora)
fimse
fimpara



Fimalgoritmo